# Generated by Django 4.0.6 on 2022-08-09 11:29

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path



DATA_FILENAME = 'export.geojson'
def load_data(apps, obj):
    Bars = apps.get_model('testproject', 'Place')
    Category = apps.get_model('testproject', 'Category')
    Cat_lst = []
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile), encoding='utf-8') as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','name:en')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    category = obj.get('amenity', 'null')


                    if category in Cat_lst:
                        pass
                    else:
                        Cat_lst.append(category)
                        Category(name=category).save()

                    Bars(name=name, location=location).save()
            except KeyError:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(["INSERT INTO testproject_category(name) VALUES ('Bar')"]),
        migrations.RunPython(load_data)
    ]


