# Generated by Django 4.0.6 on 2022-08-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_auto_20220809_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='category_id',
            new_name='category',
        ),
    ]
